import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Reckrd",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav style={{
          backgroundColor: '#1E3B57',
          color: '#fff',
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          padding: '10px 20px',
          position: 'fixed',
          width: '100%',
          top: '0',
          left: '0',
          height: '60px',
          zIndex: '1000',
        }}>
          <div>Reckrd</div>
          <div><a href="/login" style={{color: "white"}}>Welcome</a></div>
        </nav>

        <aside style={{
            position: 'fixed',
            top: '50px', 
            left: 0,
            width: '200px', 
            height: 'calc(100vh - 50px)',
            backgroundColor: '#284D73',
            color: 'white',
            display: 'flex',
            flexDirection: 'column',
            padding: '20px',
            boxShadow: '2px 0 5px rgba(0, 0, 0, 0.1)',
            zIndex: 999
          }}>
           
            
           
            <div style={{position: 'absolute', bottom: '50%', left: '100%', width: 0, height: 0, borderTop: '20px solid transparent', borderBottom: '20px solid transparent', borderLeft: '20px solid #284D73', transform: 'translateY(50%)' }}></div>
            
          </aside>

      
        <main style={{ marginTop: '60px' }}>{children}</main>
      </body>
    </html>
  );
}